### ISSUE TITLE
No more compatible with phpbb 3.2.2

### ISSUE THREAD

**Issue by PeopleInside** [melvingb/we_universal#15]
we_universal and we_clearblue are not more working on phpbb 3.2.2

**Comment by v12mike** [comment]
I will take a look (I have not tried 3.2.2 yet).

**Comment by panteror** [comment]
Thank You, i'm waiting for 3.2.2 update too.

**Comment by melvingb** [comment]
Once again, patience @PeopleInside, I'm update this style...

**Comment by ghost** [comment]
Any updates? Thanks for updating and maintaining it.

**Comment by jimsefton** [comment]
Has anyone had chance to estimate the work needed on this yet? I am keep to stay on the latest version of PHPBB, so if the theme ends up lagging behind I may need to swap.

**Comment by ghost** [comment]
Not sure, but here is the list of changes; https://gist.github.com/marc1706/dbca9c5f5686e9cb46f45f17e98916b9.

**Comment by Matevoun** [comment]
For thread follow, because we love it... ;)

**Comment by ghost** [comment]
Any news @v12mike?

**Comment by Matevoun** [comment]
Yep, please, any good news @v12mike ?

**Comment by v12mike** [comment]
I am also waiting for melvingb to announce something.  I hope that is soon.

**Comment by ghost** [comment]
Seems like no updates, anyway you can update it @v12mike?

**Comment by v12mike** [comment]
If there is no update this week, I will start doing it myself.

**Comment by jimsefton** [comment]
Thanks v12mike, that would be appreciated.

**Comment by Matevoun** [comment]
YES @v12mike  ... YES PLEASE ;-)

**Comment by v12mike** [comment]
I will be updating this style for phpBB 3.2.2.   I will report progress in a few days.

**Comment by jimsefton** [comment]
Awesome, thanks!

**Comment by Matevoun** [comment]
@v12mike THANK YOU !!! :)

**Comment by v12mike** [comment]
I have made some minor fixes to the style, and merged a couple of PRs that I had proposed a few months ago.  You can see the current version (temporarily) in action at: https://xmv6.co.uk .  This is running phpBB 3.2.2,  a real board database, but with no extensions and without images.

Please comment here if you see any problems with it.

I will work on testing it and releasing this week.

**Comment by jimsefton** [comment]
Looks good, although the banner breaks out the side when I narrow the width on Chrome (on OSX). Will do some more testing when I get chance.

**Comment by v12mike** [comment]
I have now made an adjustment for that issue (clear your browser cache to see it).

The text in the profile box on the viewtopic page is now a couple of points smaller, this is inherited from prosilver.

**Comment by v12mike** [comment]
I have made a release of we_universal for phpBB v3.2.2 on my own github account at: https://github.com/v12mike/we_universal/releases/tag/2.5.4

Please raise an issue there if you have any problems with it.

**Comment by panteror** [comment]
Hi, Thanks for update, small visual problem, i open an issue : https://github.com/v12mike/we_universal/issues/8
