### ISSUE TITLE
Forum breadcrumbs not working

### ISSUE THREAD

**Issue by jimsefton** [melvingb/we_universal#16]
Out the box, with just this style enabled and no extensions, the forum breadcrumbs looks like this:

<img width="1165" alt="Screenshot 2020-01-12 at 10 40 01" src="https://user-images.githubusercontent.com/1613164/72217588-eb8b6800-3527-11ea-9d5b-c9eca454e6a7.png">

**Comment by melvingb** [comment]
Thanks, i will check that

**Comment by melvingb** [comment]
Fixed in the next version

**Comment by PepoDance** [comment]
When will the update be available?
